# Generated by Django 3.2.9 on 2021-12-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20211202_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.posting'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='thumbnail',
            field=models.URLField(max_length=1000),
        ),
    ]
