# Generated by Django 3.2.9 on 2021-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20211206_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posting',
        ),
        migrations.AlterField(
            model_name='posting',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
