# Generated by Django 3.2.9 on 2021-12-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_subscribe'),
        ('postings', '0001_initial'),
        ('branch_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingtag',
            name='posting',
            field=models.ManyToManyField(related_name='ptags', to='postings.Posting'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ManyToManyField(related_name='utags', to='users.User'),
        ),
    ]
