# Generated by Django 3.2.9 on 2021-12-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postingspostingtags',
            constraint=models.UniqueConstraint(fields=('posting', 'posting_tag'), name='unique_posting_posting_tag'),
        ),
        migrations.AddConstraint(
            model_name='usersusertags',
            constraint=models.UniqueConstraint(fields=('user', 'user_tag'), name='unique_user_user_tag'),
        ),
    ]
