# Generated by Django 3.2.9 on 2021-12-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('branch_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersusertags',
            unique_together={('user', 'user_tag')},
        ),
    ]
