# Generated by Django 3.2.9 on 2021-12-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
        ('branch_tags', '0002_alter_usersusertags_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postingspostingtags',
            unique_together={('posting', 'posting_tag')},
        ),
    ]
