# Generated by Django 3.2.9 on 2021-12-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
        ('users', '0002_alter_user_subscribe'),
        ('branch_tags', '0003_auto_20211202_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingtag',
            name='postings',
            field=models.ManyToManyField(related_name='posting_tags', to='postings.Posting'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='users',
            field=models.ManyToManyField(related_name='user_tags', to='users.User'),
        ),
    ]
