# Generated by Django 3.2.9 on 2021-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_tags', '0004_auto_20211202_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postingtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
